### ISSUE TITLE
✨ Migrate Wiki to Docusaurus

### ISSUE THREAD

**Issue by raxhvl** [eth-protocol-fellows/protocol-studies#10]
We discussed in our town hall that one of the core objective is to gather all things Ethereum and make them readily accessible. But for this knowledge base to flourish, everyone needs to know it exists. To achieve this, I propose migrating to [Docusaurus](https://github.com/facebook/docusaurus) for our website. Here are the benefits over docsify:

- **🔍 Improved Search:** Docusaurus offers a powerful built-in search feature, making it easier for users to find information. [Algolia Doc search is free for all open source projects.](https://docusaurus.io/docs/search#using-algolia-docsearch)
- **👁‍🗨 Better SEO:** Docusaurus uses static site generation, boosting our wiki's visibility in search engines and attracting more users. [SEO support is broken for docsify](https://github.com/docsifyjs/docsify/issues/136). 
- **🧮 Math Equations:** [Support for Math Equations](https://docusaurus.io/docs/markdown-features/math-equations) and [mermaid diagrams](https://docusaurus.io/docs/markdown-features/diagrams)
- **📟 Better UX:** Lots of small features like [tabs](https://docusaurus.io/docs/markdown-features/tabs) and, the automatically generated Index page:
![image](https://github.com/eth-protocol-fellows/protocol-studies/assets/10168946/46ca9e26-301a-484a-93b5-57d496790eb5)
- **💽 [Optional] Versioning:** Ethereum landscape is evolving, we could use versions for forks.
- **📊 [Optional] Analytics:** Adding analytics can help us refine our content based on user feedback.

I am willing to take up. Existing markdown files can be easily ported over.

**Comment by raxhvl** [comment]
That makes sense. Thanks for the context.

**Comment by taxmeifyoucan** [comment]
Closing as Docsify works well for now, feel free to reopen if any new issues come up
