### ISSUE TITLE
Wiki - Protocol Overview

### ISSUE THREAD

**Issue by taxmeifyoucan** [eth-protocol-fellows/protocol-studies#152]
The Protocol overview page should give an introduction to Ethereum from technical perspective and help reader navigate through the wiki. 

https://epf.wiki/#/wiki/protocol/overview

I am not settled on what the content should exactly look like, I would be glad for inputs and collaborators on this. Kind of an updated, simplified whitepaper describing the protocol comes to mind. Generally it can be guided by the structure of the protocol with a short overview of various domains.

**Comment by raxhvl** [comment]
I'm thinking
- a general overview of how Ethereum as a world computer is fundamentally different. [This talk by gavin](https://www.youtube.com/watch?v=U_LK0t_qaPo) covers it really well:
   - Global singleton
   - Atomic, traceable state changes
   - Multi user by default
   - Provenance
- simplified white paper like you said
- maybe few interesting real word applications?

the theme being non technical what is it and how is it being used.
