### ISSUE TITLE
Wiki - Protocol Design

### ISSUE THREAD

**Issue by taxmeifyoucan** [eth-protocol-fellows/protocol-studies#154]
The page should cover design principles and rationale of the Ethereum protocol, updating to reflect the current zeitgeists and architecture evolution. 

## Protocol Design

This page is under placeholder since the wiki started https://github.com/eth-protocol-fellows/protocol-studies/blob/main/docs/wiki/protocol/design-rationale.md

It would be great to fill it because there is no up to date document explaining why Ethereum looks the way it does. The placeholder page includes a doc from old Eth builders wiki which could be revived. The core tenets are similar but lot of things can be updated, V's blog posts like the one I linked are a great resource. There are projects like [Merge Manual](https://stateful.mirror.xyz/mYXVnZ_0mP0eTtKMb1-NJqo3a8cRXGMySfk_0ep_Oeg) or recent Dencun Diaries which can also inspire the updated version.  I partially covered it in my talk on [Week 1](https://epf.wiki/#/eps/week1).

**Comment by hopinheimer** [comment]
I'd like to collaborate! @taxmeifyoucan @gorondan

**Comment by hopinheimer** [comment]
Proposed content

I'm assuming here that important updates will also contribute to the protocol design 

- [ ] fundamental principles
- [ ] accounts over UTXOs
- [ ] merkle patricia trie
- [ ] RLP
- [ ] compression algorithm
- [ ] trie
- [ ] EVM (gas and fee) 
- [ ] Casper + GHOST
- [ ] weak subjectivity 
- [ ] attestation
- [ ] London update 
- [ ] EIP-4844

@taxmeifyoucan @gorondan  @raxhvl

**Comment by taxmeifyoucan** [comment]
#262
