### ISSUE TITLE
EPF wiki template doesn't render mermaid script or references in ePBS page

### ISSUE THREAD

**Issue by thogiti** [eth-protocol-fellows/protocol-studies#173]
Our current EPF wiki template doesn't render mermaid script. It also doesn't display references at the end of page. 

For a temporary fix, I will update the ePBS to have a static image instead of mermaid script rendering and add a section for Resources. 

https://epf.wiki/#/wiki/research/PBS/ePBS

I will work on it this weekend.

**Comment by shyam-patel-kira** [comment]
> Our current EPF wiki template doesn't render mermaid script. It also doesn't display references at the end of page.
> 
> For a temporary fix, I will update the ePBS to have a static image instead of mermaid script rendering and add a section for Resources.
> 
> https://epf.wiki/#/wiki/research/PBS/ePBS
> 
> I will work on it this weekend.

Would it be beneficial to add images instead of mermaid script? And the subtitle in image can be linked to the mermaid scripts.

**Comment by thogiti** [comment]
> > Our current EPF wiki template doesn't render mermaid script. It also doesn't display references at the end of page.
> > For a temporary fix, I will update the ePBS to have a static image instead of mermaid script rendering and add a section for Resources.
> > https://epf.wiki/#/wiki/research/PBS/ePBS
> > I will work on it this weekend.
> 
> Would it be beneficial to add images instead of mermaid script? And the subtitle in image can be linked to the mermaid scripts.

Thx @shyam-patel-kira. Pushing a commit with static images in few minutes.

**Comment by taxmeifyoucan** [comment]
Thanks for bringing this up, I didn't realize it's missing in Docsify. I added a plugin for mermaid scripts and it should all render correctly now. Example from ePBS 
![image](https://github.com/eth-protocol-fellows/protocol-studies/assets/61149543/f5e5eba9-3870-4a8b-be83-37d5fe0003e3)

**Comment by thogiti** [comment]
Cool. Thx @taxmeifyoucan. 

Do we need another wiki-pages merge to see this change in the production?
