### ISSUE TITLE
Wiki - Consensus Layer

### ISSUE THREAD

**Issue by shyam-patel-kira** [eth-protocol-fellows/protocol-studies#185]
## What content is missing?
- Consensus layer architecture
- Consensus specs

## Proposed Content to cover
- [x]  Overview of CL and beacon-chain
- [x]  Slots and epochs
- [x]  Validators and attestations
- [x]  Committees
- [x]  Beacon-chain checkpoints and Finality
- [x]  Staking rewards and Penalties
- [x]  Consensus mechanisms, algorithms etc
    - [x] Fork-choice rules, BFT, pBFT
    - [x] Reorgs and Reversion
    - [x] Architecture
    - [x] State Transition function
    - [ ]  Casper FFG and LMD-Ghost
- [ ]  Consensus Specs
- [ ]  using Pyspec
- [ ]  Beacon chain apis
- [ ]  examples using the prysm client

## Related content in the wiki
- There's one PR for `cl-architecture` but it's kinda misleading cuz it only give high level overview on variation of CL clients

**Comment by ultraviolet10** [comment]
Would love to collaborate!

**Comment by taxmeifyoucan** [comment]
The structure and each page should reflect its EL counterpart to keep the same style across the wiki. 
Quick ideas on the structure: 

- The intro and overview page. Right now it's in ok state, there could be links to each section 
- CL clients, I recently updated it with list of all clients. But there needs to be more info on each, some basic tips and links. In progress #107  
- Specs, this page should explain how and where CL is specified, how to use pyspec. Based on week 6 dev presentation
- Client architecture, should follow a structure started in #184, explaining how the client works, its services and processes, inspiration in week 8 dev
- Beacon APIs page dedicated to their specification, changes and usage 
- Proof of stake diving into the consensus mechanism, explaining gasper from more abstract perspective. This was an early idea and maybe it's already covered well in eth.org docs, I don't feel strong about this one

**Comment by shyam-patel-kira** [comment]
Thanks for the suggestion @taxmeifyoucan! The update on this got slightly delayed because I was working BLS page, will get started on this
