### ISSUE TITLE
Wiki - Docs on encoding

### ISSUE THREAD

**Issue by taxmeifyoucan** [eth-protocol-fellows/protocol-studies#219]
## What content is missing?

Pages covering Eth standards for data serialization and encoding - RLP and SSZ.

## Structure

A page within EL folder should cover technical aspects and tooling for RLP. Another page in CL should cover SSZ. Ideally, there could be insights into how its implemented, sort of as annotated spec.

**Comment by thogiti** [comment]
@taxmeifyoucan I will take it. I will start with RLP and then SSZ.

**Comment by thogiti** [comment]
I completed the RLP wiki page. It is merged into the main. 
https://github.com/eth-protocol-fellows/protocol-studies/pull/232
https://github.com/eth-protocol-fellows/protocol-studies/pull/236

I am currently working on SSZ wiki page.

**Comment by thogiti** [comment]
Completed SSZ and Merkleization pages. 
https://github.com/eth-protocol-fellows/protocol-studies/pull/244/
