### ISSUE TITLE
Fix  devp2p section on architecture-overview.png diagram. 

### ISSUE THREAD

**Issue by meldsun0** [eth-protocol-fellows/protocol-studies#228]
## What content is missing?

The diagram  shows that devp2p uses UDP. While this is true, it is only on the discovery phase. During runtime (when sending messages around ) it uses TCP. 

- Here is diagrama: https://github.com/eth-protocol-fellows/protocol-studies/blob/main/docs/images/el-architecture/architecture-overview.png
- Here is referenced: https://github.com/eth-protocol-fellows/protocol-studies/blob/main/docs/wiki/EL/el-architecture.md

@SiddharthV1  I guess you contributed on this. Can you take a look?

**Comment by SiddharthV1** [comment]
@meldsun0 That's great that you found an issue,this fast!  please fix it if you know how, there are exaclidraw files inside images/el-archetecture/excalidraw, you can edit them easily to improve or fix  the image, I let me know how I can help!

**Comment by meldsun0** [comment]
Great thanks! If you need some help! Let me know.
