### ISSUE TITLE
Wiki - EL Specs page

### ISSUE THREAD

**Issue by SiddharthV1** [eth-protocol-fellows/protocol-studies#231]
## What content is missing?
Execution Layer Specs.
## Related content in the wiki
Execution Layer Architecture (STF, Payload Validation & block validation during state sync), MPT, RLP, EVM
## Other relevant resources 
https://github.com/ethereum/execution-specs
https://ethereum.github.io/yellowpaper/paper.pdf

**Comment by MayowaObisesan** [comment]
Hi @SiddharthV1. I noticed the collaboration tag. I'll like to contribute to this.

**Comment by SiddharthV1** [comment]
@MayowaObisesan That's great! First things first, all of the content from week 6 el-specs presentation (https://epf.wiki/#/eps/week6-dev) needs to be added. A few of the topics mentioned in the presentation are already covered on the page in the el-specs branch; the introduction may simply cross-reference those, but the main idea was to add the topics that are not already covered and bring over the 30-second tour from the presentation as an introduction. We also need to add the demo that was shown at the conclusion of the presentation. You can also find me in the EPF study group discord (@sidVdr) and DM me there for any questions

**Comment by MayowaObisesan** [comment]
Thanks for reaching out ASAP. I'll start from the link you sent.

I'll definitely DM if I have any questions.
