### ISSUE TITLE
Builders and searchers are being used interchangeably on mev-boost

### ISSUE THREAD

**Issue by aslikaya** [eth-protocol-fellows/protocol-studies#268]
Although builders may sometimes act as searchers and include transactions with MEV opportunities themselves, they have more responsibilities like building execution payloads so it is better not to use those interchangeably.

**Comment by raxhvl** [comment]
Thanks for flagging this @aslikaya. Feel free to work on this.

**Comment by aslikaya** [comment]
I actually worked on it but waiting for the author's look on the changes to open the PR (as mentioned in PR checklist)

**Comment by taxmeifyoucan** [comment]
Thanks for the PR! This is resolved #271
