### ISSUE TITLE
Clarify Purpose and Intent of Source Code Mirror

### ISSUE THREAD

**Issue by emnul** [eth-protocol-fellows/protocol-studies#297]
## What content is missing?
In the [Contributing page -> Contributing section](https://epf.wiki/#/contributing?id=contributing) there's a "Mirrored at //TODO" item. The purpose of this issue to clarify the purpose and intent of this item. Is the intention to host the source code on a decentralized platform such as [Radicle](https://radicle.xyz/)? If so, who will be responsible for managing the mirror?

**Comment by taxmeifyoucan** [comment]
The long term plan is to have the content of the repo mirrored somewhere for redundancy and decentralization, yes. One possible possible solution is Radicle. There is also EF devops hosted gitea/gitlab which is automatically pulling all ethereum repos and we should add this one. So ideally there will be multiple mirrors. 

Thanks for bringing this up, I believe the current state of the wiki is already worth mirroring. We can discuss it on the next wiki contributors call

**Comment by raxhvl** [comment]
I checked radicle. We could have a github action that connects to a server to keep the radical mirror in sync. This server could be org wide keeping several radicle mirrors in sync with the added advantage that the server will have a local copy of the repos. We'll loose artificats such as issues + PRs though.

**Comment by taxmeifyoucan** [comment]
Yes github only stuff like issues cannot be transferred right now. Last time I checked, git tea had some sort of support for issues and PRs as well but limited. 

@gorondan Setup a rad repo, he should give you access and it should be automatically pulled

**Comment by gorondan** [comment]
> @gorondan Setup a rad repo, he should give you access and it should be automatically pulled

We'll get aligned on that, +1 for automation @raxhvl

**Comment by gorondan** [comment]
Code Source mirroring clarified

**Comment by taxmeifyoucan** [comment]
@gorondan it's not at this moment. Can you share link to the mirror?

**Comment by gorondan** [comment]
> @gorondan it's not at this moment. Can you share link to the mirror? 
> 
The purpose and intent is clarified. That's why I closed the issue on the topic itself. Granted, we can keep it open until the actual link gets posted

**Comment by taxmeifyoucan** [comment]
@gorondan We just need to add it to docs. Do you have link to the radicle mirror?
