### ISSUE TITLE
Wiki contributors meeting #5

### ISSUE THREAD

**Issue by raxhvl** [eth-protocol-fellows/protocol-studies#299]
## Meeting Info

The 5th call dedicated to coordination of EPF wiki contributors. If you contributed or plan to work on content in the wiki, please join our call. We will discuss current state of the wiki, outstanding issues and gather feedback. Feel free to comment below if there are any areas you would like to discuss. 

Apart from this call, async discussion is in #wiki-contributors channel in EPS discord. 

   - Date: -  [July 25, 2024, 3PM UTC](https://www.timeanddate.com/worldclock/converter.html?iso=20240725T150000&p1=1440&p2=37&p3=136&p4=237&p5=923&p6=204&p7=671&p8=16&p9=41&p10=107&p11=28)
   - Call: https://meet.ethereum.org/EPFwiki
   - Discussion: Join the EPFsg Discord and visit `wiki-writers` channel

### Agenda
- State of the wiki, items in progress since the last call
- #297 
- EPF contributions
- Propose your agenda points in comments 👇

**Comment by Inspector-Butters** [comment]
One point I would like to discuss is that, since a lot of the EPF fellows are working on Ethereum clients and probably have to study and understand at least some portion of them, and since the resources for understanding the codebase and flow of those clients are usually non existent, there is a good opportunity to build those resources collaboratively and the "clients" section in both execution layer and consensus layers of the wiki are a good place for them.

**Comment by raxhvl** [comment]
> One point I would like to discuss is that, since a lot of the EPF fellows are working on Ethereum clients and probably have to study and understand at least some portion of them, and since the resources for understanding the codebase and flow of those clients are usually non existent, there is a good opportunity to build those resources collaboratively and the "clients" section in both execution layer and consensus layers of the wiki are a good place for them.

I was thinking the same. A lot of EPF research work can be hosted on the wiki. I'm hoping to do the same. We may need to let the fellows know about this.

**Comment by shyam-patel-kira** [comment]
let's also discuss pending PRs

**Comment by KatyaRyazantseva** [comment]
I would like to contribute into testing using Kurtosis

**Comment by Tomi-3-0** [comment]
I would like to write a detailed article on 'Implementing an eip'

**Comment by gorondan** [comment]
> I would like to write a detailed article on 'Implementing an eip'

https://github.com/ethereum/EIPs/blob/master/EIPS/eip-7723.md
