### ISSUE TITLE
high res roadmap img

### ISSUE THREAD

**Issue by gorondan** [eth-protocol-fellows/protocol-studies#91]
we need a hig res version of the [roadmap image](https://github.com/eth-protocol-fellows/protocol-studies/pull/78/files#diff-56bb6e406b7396c6ce49450c1d60c634813cc5a86156e5bd0fbe7a08d95aa8fe)

**Comment by taxmeifyoucan** [comment]
https://twitter.com/VitalikButerin/status/1741190491578810445/photo/1

**Comment by gorondan** [comment]
> https://twitter.com/VitalikButerin/status/1741190491578810445/photo/1

that's actually the one in the SG repo, I got it from the source you posted. 
but it's low res
asked @domothyb if he has a better one, I think there's a big chance

**Comment by taxmeifyoucan** [comment]
The version in repo is smaller res than the original from twitter, you can just switch to this one. But if there is some svg original, it would be cool. 
680 × 678 vs 1286 × 1282
