### ISSUE TITLE
PBS wiki page

### ISSUE THREAD

**Issue by taxmeifyoucan** [eth-protocol-fellows/protocol-studies#93]
Proposer builder separation is necessary to understand the current state of Ethereum protocol and discussions around it. PBS should be documented in the wiki, here is a rough outline on what should be included: 

- Quick intro, what the page will cover
- Insight into consensus layer
   - Explaining role of the builder
   - Explain role of the proposal 
- Current state
   - default behavior 
   -  PBS and relationship of relays, builders and validators
   - mevboost, documenting what is it, how it works
   -  issues stemming from this (security, third party dependency, censorship etc) 
 - Proposed solutions, current R&D
   - ePBS, inclusion lists, PEPC, etc
  - Collection of resources
    - all hackmds, ethresearch posts and related articles, videos, papers you stumble upon

**Comment by raxhvl** [comment]
This is pretty new to me. Do you know where in the sidebar should this come?

**Comment by shyam-patel-kira** [comment]
I'm creating WIP PR for this one, it is open for collaboration

**Comment by shyam-patel-kira** [comment]
Creating a checklist here, for tracking purposes

- [x] Quick intro, what the page will cover
- [x] Insight into consensus layer
    - [x] Explaining role of the builder
    - [x] Explain role of the proposal
- [x] Current state
    - [x] default behavior
    - [x] PBS and relationship of relays, builders and validators
    - [ ] mevboost, documenting what is it, how it works
    - [x] issues stemming from this (security, third party dependency, censorship etc)
- [ ] Proposed solutions, current R&D
    - [ ] ePBS
    - [ ] 2-slot PBS
    - [ ] inclusion lists
- [ ] Collection of resources
    - [ ] all hackmds, ethresearch posts and related articles, videos, papers you stumble upon

**Comment by shyam-patel-kira** [comment]
I'm currently working on mev-boost and ePBS. Adding the comment to avoid confusion, promote collaborative effort

**Comment by thogiti** [comment]
I am working on ePBS.

https://github.com/thogiti/protocol-studies/blob/pbs/docs/wiki/research/PBS/ePBS.md

PR:
https://github.com/eth-protocol-fellows/protocol-studies/pull/115

**Comment by thogiti** [comment]
May I suggest to remove ePBS solutions section from the `PBS.md` page. 

I am working on a detailed ePBS page at https://github.com/eth-protocol-fellows/protocol-studies/pull/118.

**Comment by taxmeifyoucan** [comment]
ePBS deserves its own page for sure but it still should be mentioned and linked in the main pbs doc. Just a high level overview with link to details in the separate page

**Comment by shyam-patel-kira** [comment]
Sorry for the late update from my side. I've update my PR with current changes and also included link to future ePBS entry. I'm not able to request a review though, so tagging you here @taxmeifyoucan

**Comment by gorondan** [comment]
I'm working on PEPC and ETs, because I cover roles separation in general, including my research on enshrined Operator-Delegator Separation.

> ePBS deserves its own page for sure but it still should be mentioned and linked in the main pbs doc. Just a high level overview with link to details in the separate page
With ePBS, PEPC, Execution Tickets and Rainbow staking being in active research, the vectors seem to be pointing towards an enshrining of roles separation era to come. wdyt guys? should we have a separate section on Roles Separation, curated by EPF sg?

**Comment by thogiti** [comment]
Hi @gorondan.

I have briefly covered PEPC as a solution to ePBS in my PR at https://github.com/eth-protocol-fellows/protocol-studies/pull/115/commits/3aac3f606ecaecd5f8fdda6b0448c7a64541b850.
 
But, I think, PEPC and ET definitely deserve their own page.

**Comment by thogiti** [comment]
Hi @shyam-patel-kira @arynyestos 

I think my PR on ePBS https://github.com/eth-protocol-fellows/protocol-studies/pull/115 is showing some conflicts on `pbs.md`. Can you please check your latest changes to `pbs.md`? 

Can you please let me know what is your latest commit hash for `pbs.md`?

I think the `pbs.md` merge action is waiting for resolving these content conflict.
